CREATE USER IF NOT EXISTS SVC_CICD
    LOGIN_NAME = 'SVC_CICD'
    DISPLAY_NAME = 'SVC_CICD'
    PASSWORD = 'IGNORE_THIS_VALUE_HAS_BEEN_UPDATED'
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_WAREHOUSE = DEV_WH
    MUST_CHANGE_PASSWORD = TRUE;
