-- warehouse permissions
GRANT USAGE, OPERATE ON WAREHOUSE DEV_WH TO ROLE CICD_ALL_ROLE;

-- database & schema permissions
GRANT USAGE ON DATABASE {database} TO ROLE CICD_ALL_ROLE; --noqa
GRANT USAGE ON ALL SCHEMAS IN DATABASE {database} TO ROLE CICD_ALL_ROLE; --noqa
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {database} TO ROLE CICD_ALL_ROLE; --noqa
GRANT USAGE, CREATE TABLE ON ALL SCHEMAS IN DATABASE {database} TO ROLE CICD_ALL_ROLE; --noqa
GRANT USAGE, CREATE TABLE ON FUTURE SCHEMAS IN DATABASE {database} TO ROLE CICD_ALL_ROLE; --noqa
GRANT SELECT, DELETE, INSERT ON ALL TABLES IN DATABASE {database} TO ROLE CICD_ALL_ROLE; --noqa
GRANT SELECT ON ALL VIEWS IN DATABASE {database} TO ROLE CICD_ALL_ROLE; --noqa

-- grants, user & role permissions
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE CICD_ALL_ROLE;
GRANT CREATE USER ON ACCOUNT TO ROLE CICD_ALL_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE CICD_ALL_ROLE;
