!SET variable_substitution=true;
--give base privileges to the &{PROGRAM}_DBA roles
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE &{PROGRAM}_DBA;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE &{PROGRAM}_DBA;
