!SET variable_substitution=true;
--define the role hierarchy
USE ROLE SECURITYADMIN;
GRANT ROLE &{PROGRAM}_&{ENV}_DBA TO ROLE SYSADMIN;
GRANT ROLE &{PROGRAM}_&{ENV}_DBT_SVC TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_DEVELOPER TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_ANALYST TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_VISUALISER TO ROLE &{PROGRAM}_&{ENV}_ANALYST;

--grant &{PROGRAM}_&{ENV}_SF_TASK_ADMIN, &{PROGRAM}_&{ENV}_SF_STAGE_ADMIN and &{PROGRAM}_&{ENV}_SF_SI_ADMIN roles to &{PROGRAM}_&{ENV}_DBA
GRANT ROLE &{PROGRAM}_&{ENV}_SF_TASK_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_SF_STAGE_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_SF_SI_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT ROLE &{PROGRAM}_&{ENV}_SF_TAG_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DBA;

--developer role permissions
--1. DEVELOPER role is required to load new data into Snowflake (i.e. be assigned the data_loader role)
GRANT ROLE &{PROGRAM}_&{ENV}_DATA_LOADER TO ROLE &{PROGRAM}_&{ENV}_DEVELOPER;
--2. DATA_LOADER role is required to create new Snowflake tasks (i.e. be assigned the SF_TASK_ADMIN role)
GRANT ROLE &{PROGRAM}_&{ENV}_SF_TASK_ADMIN TO ROLE &{PROGRAM}_&{ENV}_DATA_LOADER;
--3. DBT_SVC requires the same permissions as the developer role
GRANT ROLE &{PROGRAM}_&{ENV}_DEVELOPER TO ROLE &{PROGRAM}_&{ENV}_DBT_SVC;
GRANT ROLE &{PROGRAM}_&{ENV}_DATA_LOADER TO ROLE &{PROGRAM}_&{ENV}_DBT_SVC;
