!SET variable_substitution=true;
USE ROLE AGDF_DBA;
USE WAREHOUSE AGDF_DEVELOPER_WH;
USE DATABASE &{ENV}_AGDF_RAW_DB;
USE SCHEMA UTILITIES;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FMT
    TYPE = PARQUET
    TRIM_SPACE = TRUE
    NULL_IF = ('\\N');

CREATE STAGE IF NOT EXISTS CHEQUEGUARD_STAGE
    STORAGE_INTEGRATION = AGDF_S3_INT
    URL = 's3://agdf-dev-chkguard-curated-135040590354-dev-master';

CREATE STAGE IF NOT EXISTS SIRIUS_STAGE
    STORAGE_INTEGRATION = AGDF_S3_INT
    URL = 's3://agdf-curated-135040590354-dev-master';
