!SET variable_substitution=true;
USE ROLE AGDF_DBA;
USE WAREHOUSE AGDF_DEVELOPER_WH;

--quickly drop the dbs
DROP DATABASE IF EXISTS &{ENV}_AGDF_RAW_DB;
DROP DATABASE IF EXISTS &{ENV}_AGDF_CURATED_DB;
DROP DATABASE IF EXISTS &{ENV}_AGDF_ANALYTICS_DB;
