!SET variable_substitution=true;

-- Grant future ownership of schemas, tables and views to 'AGDF_DBA' role
USE ROLE SECURITYADMIN;
GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE &{ENV}_AGDF_ANALYTICS_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE TABLES IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE TABLES IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE TABLES IN DATABASE &{ENV}_AGDF_ANALYTICS_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE VIEWS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE VIEWS IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DBA;
GRANT OWNERSHIP ON FUTURE VIEWS IN DATABASE &{ENV}_AGDF_ANALYTICS_DB TO ROLE AGDF_DBA;

--raw db
GRANT USAGE ON DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT USAGE ON DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DATA_LOADER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DATA_LOADER;
GRANT USAGE ON ALL STAGES IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT USAGE ON ALL STAGES IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DATA_LOADER;
GRANT USAGE ON ALL FILE FORMATS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT USAGE ON ALL FILE FORMATS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DATA_LOADER;
GRANT SELECT ON ALL TABLES IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON ALL VIEWS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON ALL EXTERNAL TABLES IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_ANALYST;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT CREATE EXTERNAL TABLE, CREATE MATERIALIZED VIEW ON ALL SCHEMAS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DATA_LOADER;

GRANT USAGE ON FUTURE STAGES IN SCHEMA &{ENV}_AGDF_RAW_DB.UTILITIES TO ROLE AGDF_DEVELOPER;
GRANT USAGE ON FUTURE STAGES IN SCHEMA &{ENV}_AGDF_RAW_DB.UTILITIES TO ROLE AGDF_DATA_LOADER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA &{ENV}_AGDF_RAW_DB.UTILITIES TO ROLE AGDF_DEVELOPER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA &{ENV}_AGDF_RAW_DB.UTILITIES TO ROLE AGDF_DATA_LOADER;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN DATABASE &{ENV}_AGDF_RAW_DB TO ROLE AGDF_DATA_LOADER;

--curated db
GRANT USAGE ON DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DEVELOPER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE MATERIALIZED VIEW ON ALL SCHEMAS IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DEVELOPER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON ALL VIEWS IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE &{ENV}_AGDF_CURATED_DB TO ROLE AGDF_DEVELOPER;

--analytics db
GRANT USAGE ON DATABASE &{ENV}_AGDF_ANALYTICS_DB TO ROLE AGDF_DEVELOPER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE ON ALL SCHEMAS IN DATABASE &{ENV}_AGDF_ANALYTICS_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN DATABASE &{ENV}_AGDF_ANALYTICS_DB TO ROLE AGDF_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE &{ENV}_AGDF_ANALYTICS_DB TO ROLE AGDF_DEVELOPER;
