AWSTemplateFormatVersion: '2010-09-09'

Description: >
  IAM role to allow comms from Snowflake

Parameters:
  IAMRoleName:
    Type: String
  TrustedAccountID:
    Type: String

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleName
      Description: IAM role used to allow comms between Snowflake and AWS
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: [!Ref TrustedAccountID]
            Action: ['sts:AssumeRole']
