!SET variable_substitution=true;
USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_DEVELOPER_WH_RM TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_LOADING_WH_RM TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_REPORTING_WH_RM TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_TRANSFORMATION_WH_RM TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_SP_TRANSFORMATION_WH_RM TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_TRANSFORMATION_LRG_WH_RM TO ROLE &{PROGRAM}_DBA;
