!SET variable_substitution=true;
USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_DEVELOPER_WH TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_LOADING_WH TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_REPORTING_WH TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_TRANSFORMATION_WH TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_SP_TRANSFORMATION_WH TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_TRANSFORMATION_LRG_WH TO ROLE &{PROGRAM}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_DEVELOPER_WH TO ROLE &{PROGRAM}_DBA;
