USE ROLE ${PROGRAM}_${ENV}_DATA_LOADER;
USE WAREHOUSE ${PROGRAM}_${ENV}_LOADING_WH;
USE DATABASE ${PROGRAM}_${ENV}_RAW_DB;
USE SCHEMA UTILITIES;

CREATE EXTERNAL TABLE IF NOT EXISTS &{DATA_SRC}.EXT_&{EG_TBL}
    WITH LOCATION = @${DATA_SRC}_STAGE
    FILE_FORMAT = UTILITIES.PARQUET_FMT
    PATTERN = '.*\{S3_FILE_PATH}/(?:.*)(?:\.parquet)';
