!SET variable_substitution=true;
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;

DROP INTEGRATION IF EXISTS &{PROGRAM}_&{ENV}_S3_INT;

DROP DATABASE IF EXISTS &{PROGRAM}_&{ENV}_RAW_DB;
DROP DATABASE IF EXISTS &{PROGRAM}_&{ENV}_CURATED_DB;
DROP DATABASE IF EXISTS &{PROGRAM}_&{ENV}_ANALYTICS_DB;

DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_LOADING_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_TRANSFORMATION_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_TRANSFORMATION_LRG_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_SP_TRANSFORMATION_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_REPORTING_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_DEVELOPER_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_DEVELOPER_WH;

USE ROLE &{PROGRAM}_&{ENV}_DBA;
DROP RESOURCE MONITOR IF EXISTS &{PROGRAM}_&{ENV}_DEVELOPER_WH_RM;
DROP RESOURCE MONITOR IF EXISTS &{PROGRAM}_&{ENV}_REPORTING_WH_RM;
DROP RESOURCE MONITOR IF EXISTS &{PROGRAM}_&{ENV}_LOADING_WH_RM;
DROP RESOURCE MONITOR IF EXISTS &{PROGRAM}_&{ENV}_TRANSFORMATION_WH_RM;
DROP RESOURCE MONITOR IF EXISTS &{PROGRAM}_&{ENV}_TRANSFORMATION_LRG_WH_RM;
DROP RESOURCE MONITOR IF EXISTS &{PROGRAM}_&{ENV}_SP_TRANSFORMATION_WH_RM;

USE ROLE ACCOUNTADMIN;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_DBA;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_DATA_LOADER;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_DEVELOPER;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_ANALYST;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_VISUALISER;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_DBT_SVC;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_SF_TASK_ADMIN;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_SF_STAGE_ADMIN;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_RM_ADMIN;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_SF_SI_ADMIN;
DROP ROLE IF EXISTS &{PROGRAM}_&{ENV}_SF_TAG_ADMIN;
