!SET variable_substitution=true;
USE ROLE &{PROGRAM}_DBA;
USE WAREHOUSE &{PROGRAM}_DEVELOPER_WH;
USE DATABASE &{PROGRAM}_RAW_DB;
USE SCHEMA UTILITIES;

CREATE FILE FORMAT IF NOT EXISTS CSV_FMT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    TRIM_SPACE = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';
