!SET variable_substitution=true;
USE ROLE SECURITYADMIN;
GRANT ROLE &{PROGRAM}_DBA TO USER PAUL999;
GRANT ROLE &{PROGRAM}_DBT_SVC TO USER PAUL999;
--GRANT ROLE ACCOUNTADMIN TO USER &{PROGRAM}_SNOWFLAKE_PIPELINE_DEPLOYMENT_USER;
