!SET variable_substitution=true;
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;

CREATE STORAGE INTEGRATION IF NOT EXISTS &{PROGRAM}_&{ENV}_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::&AWS_ACCOUNT_ID:role/&IAMROLENAME'
    STORAGE_ALLOWED_LOCATIONS = ('&ALLOWED_S3_LOCATIONS');
