!SET variable_substitution=true;
USE ROLE ${PROGRAM}_${ENV}_DBA;
USE WAREHOUSE ${PROGRAM}_${ENV}_DEVELOPER_WH;

ALTER STORAGE INTEGRATION &ST_INT_NAME
SET STORAGE_ALLOWED_LOCATIONS = ('&ALLOWED_S3_LOCATIONS');
