USE DATABASE {database}; -- noqa
USE SCHEMA {schema}; -- noqa

CREATE TABLE IF NOT EXISTS CHANGE_HISTORY (
    VERSION VARCHAR -- noqa
    , DESCRIPTION VARCHAR
    , SCRIPT VARCHAR
    , SCRIPT_TYPE VARCHAR
    , CHECKSUM VARCHAR
    , EXECUTION_TIME NUMBER
    , STATUS VARCHAR
    , INSTALLED_BY VARCHAR
    , INSTALLED_ON TIMESTAMP_LTZ
);
