!SET variable_substitution=true;
USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_&{ENV}_DEVELOPER_WH_RM TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_&{ENV}_LOADING_WH_RM TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_&{ENV}_REPORTING_WH_RM TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_&{ENV}_TRANSFORMATION_WH_RM TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_&{ENV}_SP_TRANSFORMATION_WH_RM TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON RESOURCE MONITOR &{PROGRAM}_&{ENV}_TRANSFORMATION_LRG_WH_RM TO ROLE &{PROGRAM}_&{ENV}_DBA;
