!SET variable_substitution=true;
USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_&{ENV}_LOADING_WH TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_&{ENV}_REPORTING_WH TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_&{ENV}_TRANSFORMATION_WH TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_&{ENV}_SP_TRANSFORMATION_WH TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_&{ENV}_TRANSFORMATION_LRG_WH TO ROLE &{PROGRAM}_&{ENV}_DBA;
GRANT OWNERSHIP ON WAREHOUSE &{PROGRAM}_DEVELOPER_WH TO ROLE &{PROGRAM}_&{ENV}_DBA;
