!SET variable_substitution=true;
USE ROLE &{PROGRAM}_DATA_LOADER;
USE WAREHOUSE &{PROGRAM}_LOADING_WH;
USE DATABASE &{PROGRAM}_RAW_DB;

CREATE TABLE IF NOT EXISTS AIRFLOW_ETL_CONTROL_TBL (
    DAG_NAME VARCHAR NOT NULL
    , DAG_STATE VARCHAR NOT NULL
    , EXECUTION_DATE TIMESTAMP_NTZ NOT NULL
    , START_DATE VARCHAR NOT NULL
    , END_DATE TIMESTAMP_NTZ NOT NULL
    , DURATION VARCHAR NOT NULL
    , DAG_TASK_NAME VARCHAR NOT NULL
    , DAG_TASK_STATE VARCHAR NOT NULL
    , DAG_TASK_EXECUTION_DATE TIMESTAMP_NTZ NOT NULL
    , DAG_TASK_START_DATE TIMESTAMP_NTZ NOT NULL
    , DAG_TASK_END_DATE TIMESTAMP_NTZ NOT NULL
    , DAG_TASK_DURATION VARCHAR NOT NULL
    , LOAD_TS TIMESTAMP_NTZ NOT NULL
    --schedule?
    --last_run?
    --next_run?
    --table(s) populated?
    --tbl rowcount
);
