!SET variable_substitution=true;
USE ROLE &{PROGRAM}_&{ENV}_DBA;
USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;
USE DATABASE &{PROGRAM}_&{ENV}_RAW_DB;
USE SCHEMA UTILITIES;

CREATE STAGE IF NOT EXISTS EG_STAGE
    STORAGE_INTEGRATION = &{PROGRAM}_&{ENV}_S3_INT
    URL = 's3://&{S3_BUCKET_PATH}';
