!SET variable_substitution=true;
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS &{PROGRAM}_DEVELOPER_WH_RM WITH CREDIT_QUOTA = 10,
    FREQUENCY = 'WEEKLY',
    START_TIMESTAMP = 'IMMEDIATELY',
    END_TIMESTAMP = NULL
    TRIGGERS    ON 80 PERCENT DO SUSPEND
                ON 90 PERCENT DO SUSPEND_IMMEDIATE
                ON 75 PERCENT DO NOTIFY;

CREATE RESOURCE MONITOR IF NOT EXISTS &{PROGRAM}_DEVELOPER_WH_RM WITH CREDIT_QUOTA = 10,
    FREQUENCY = 'WEEKLY',
    START_TIMESTAMP = 'IMMEDIATELY',
    END_TIMESTAMP = NULL
    TRIGGERS    ON 80 PERCENT DO SUSPEND
                ON 90 PERCENT DO SUSPEND_IMMEDIATE
                ON 75 PERCENT DO NOTIFY;

CREATE RESOURCE MONITOR IF NOT EXISTS &{PROGRAM}_REPORTING_WH_RM WITH CREDIT_QUOTA = 15,
    FREQUENCY = 'WEEKLY',
    START_TIMESTAMP = 'IMMEDIATELY',
    END_TIMESTAMP = NULL
    TRIGGERS    ON 80 PERCENT DO SUSPEND
                ON 90 PERCENT DO SUSPEND_IMMEDIATE
                ON 75 PERCENT DO NOTIFY;

CREATE RESOURCE MONITOR IF NOT EXISTS &{PROGRAM}_LOADING_WH_RM WITH CREDIT_QUOTA = 10,
    FREQUENCY = 'WEEKLY',
    START_TIMESTAMP = 'IMMEDIATELY',
    END_TIMESTAMP = NULL
    TRIGGERS    ON 80 PERCENT DO SUSPEND
                ON 90 PERCENT DO SUSPEND_IMMEDIATE
                ON 75 PERCENT DO NOTIFY;

CREATE RESOURCE MONITOR IF NOT EXISTS &{PROGRAM}_TRANSFORMATION_WH_RM WITH CREDIT_QUOTA = 10,
    FREQUENCY = 'WEEKLY',
    START_TIMESTAMP = 'IMMEDIATELY',
    END_TIMESTAMP = NULL
    TRIGGERS    ON 80 PERCENT DO SUSPEND
                ON 90 PERCENT DO SUSPEND_IMMEDIATE
                ON 75 PERCENT DO NOTIFY;

CREATE RESOURCE MONITOR IF NOT EXISTS &{PROGRAM}_SP_TRANSFORMATION_WH_RM WITH CREDIT_QUOTA = 15,
    FREQUENCY = 'WEEKLY',
    START_TIMESTAMP = 'IMMEDIATELY',
    END_TIMESTAMP = NULL
    TRIGGERS    ON 80 PERCENT DO SUSPEND
                ON 90 PERCENT DO SUSPEND_IMMEDIATE
                ON 75 PERCENT DO NOTIFY;

CREATE RESOURCE MONITOR IF NOT EXISTS &{PROGRAM}_TRANSFORMATION_LRG_WH_RM WITH CREDIT_QUOTA = 15,
    FREQUENCY = 'WEEKLY',
    START_TIMESTAMP = 'IMMEDIATELY',
    END_TIMESTAMP = NULL
    TRIGGERS    ON 80 PERCENT DO SUSPEND
                ON 90 PERCENT DO SUSPEND_IMMEDIATE
                ON 75 PERCENT DO NOTIFY;
