!SET variable_substitution=true;
USE ROLE &{PROGRAM}_&{ENV}_DBA;
USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;
USE DATABASE &{PROGRAM}_&{ENV}_RAW_DB;
USE SCHEMA UTILITIES;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FMT
    TYPE = PARQUET
    TRIM_SPACE = TRUE
    NULL_IF = ('\\N');
