!SET variable_substitution=true;
USE ROLE &{PROGRAM}_&{ENV}_DATA_LOADER;
USE WAREHOUSE &{PROGRAM}_&{ENV}_LOADING_WH;
USE DATABASE &{PROGRAM}_&{ENV}_RAW_DB;
USE SCHEMA &{DATA_SRC};

CREATE TABLE IF NOT EXISTS EXAMPLE_TBL AS
    SELECT      value:c1::int AS EXAMPLE_FILED
                , SYS_SRC_FILENAME
                , 'DATA_SRC' AS SYS_LOAD_SRC
                , TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP) AS SYS_LOAD_TS
    FROM EXT_{DATA_SRC};
