!SET variable_substitution=true;
/*
USE ROLE ACCOUNTADMIN;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_LOADING_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_TRANSFORMATION_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_REPORTING_WH;
DROP WAREHOUSE IF EXISTS &{PROGRAM}_&{ENV}_DEVELOPER_WH;
*/

USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS &{PROGRAM}_DEVELOPER_WH WITH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = &{PROGRAM}_&{ENV}_DEVELOPER_WH_RM
    -- TAG (COST_CENTER = 'development')
    COMMENT = 'Used for generic Snowflake DB object creation, outside of environment-specific DBs.';

CREATE WAREHOUSE IF NOT EXISTS &{PROGRAM}_&{ENV}_DEVELOPER_WH WITH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = &{PROGRAM}_&{ENV}_DEVELOPER_WH_RM
    -- TAG (COST_CENTER = 'development')
    COMMENT = 'Used for Snowflake DB object creation.';

USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;
CREATE WAREHOUSE IF NOT EXISTS &{PROGRAM}_&{ENV}_LOADING_WH WITH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = &{PROGRAM}_&{ENV}_LOADING_WH_RM
    -- TAG (COST_CENTER = 'data-loading-queries')
    COMMENT = 'Used to process data load/unload activities on the &{PROGRAM}_RAW DB .';

USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;
CREATE WAREHOUSE IF NOT EXISTS &{PROGRAM}_&{ENV}_TRANSFORMATION_WH WITH
    WAREHOUSE_SIZE = SMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = &{PROGRAM}_&{ENV}_TRANSFORMATION_WH_RM
    -- TAG (COST_CENTER = 'data-transform-queries')
    COMMENT = 'Used to perform data transformations between databases.';

USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;
CREATE WAREHOUSE IF NOT EXISTS &{PROGRAM}_&{ENV}_TRANSFORMATION_LRG_WH WITH
    WAREHOUSE_SIZE = MEDIUM
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = &{PROGRAM}_&{ENV}_TRANSFORMATION_LRG_WH_RM
    -- TAG (COST_CENTER = 'data-transform-queries')
    COMMENT = 'Used to perform larger data transformations between databases.';

USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;
CREATE WAREHOUSE IF NOT EXISTS &{PROGRAM}_&{ENV}_SP_TRANSFORMATION_WH WITH
    WAREHOUSE_SIZE = MEDIUM
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = &{PROGRAM}_&{ENV}_SP_TRANSFORMATION_WH_RM
    -- TAG (COST_CENTER = 'data-transform-queries')
    COMMENT = 'Used to perform data transformations between databases, using stored procs.';

USE WAREHOUSE &{PROGRAM}_&{ENV}_DEVELOPER_WH;
CREATE WAREHOUSE IF NOT EXISTS &{PROGRAM}_&{ENV}_REPORTING_WH WITH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = &{PROGRAM}_&{ENV}_REPORTING_WH_RM
    -- TAG (COST_CENTER = 'presentation-layer-queries')
    COMMENT = 'Used to process queries performed through Tableau.';
