!SET variable_substitution=true;
USE ROLE &{PROGRAM}_DBA;
USE WAREHOUSE &{PROGRAM}_DEVELOPER_WH;
USE DATABASE &{PROGRAM}_RAW_DB;
USE SCHEMA UTILITIES;

CREATE STAGE IF NOT EXISTS &{PROGRAM}_STAGE
    FILE_FORMAT = CSV_FMT;
